---

language: python

install:
  - pip install ansible

script:
  - ansible-playbook -i inventory.ini -u root travis.yml
  - ansible-playbook -i inventory.ini -u root site.yml --private-key=~/vault --diff
