---

- hosts: servers
  handlers:
    - name: reload systemd and restart Konstructs
      command: systemctl daemon-reload
      notify: restart konstructs
    - name: restart konstructs
      service: name=konstructs state=restarted enabled=yes
    - name: reload nginx
      service: name=nginx state=reloaded

  tasks:
    - name: Set up authorized_keys for root
      authorized_key: user=roor key="{{ item }}"
      with_items: "{{ konstructs_ssh_keys }}"

    - name: Install packages (Common)
      apt: name={{ item }} update_cache=yes
      with_items:
        - fail2ban
        - nginx

    - name: Install packages (Ubuntu)
      apt: name={{ item }} update_cache=yes
      with_items:
        - openjdk-8-jre-headless
      when: ansible_distribution_release == "xenial"

    - name: Install packages (Debian)
      apt: name={{ item }} update_cache=yes
      with_items:
        - openjdk-7-jre-headless
      when: ansible_distribution_release == "jessie"

    - name: Add konstructs user
      user:
        name: "{{ konstructs_user }}"
        comment: "A user for the konstructs game server"
        home: "{{ konstructs_path }}"
        system: yes

    - name: Download konstructs from bintray (sha256 verify)
      get_url:
        sha256sum: "{{ konstructs_jar_sha256 }}"
        url: "{{ konstructs_jar_url }}"
        dest: "{{ konstructs_path }}/{{ konstructs_jar }}"
        force: yes
      notify: reload systemd and restart Konstructs
      when: konstructs_jar_sha256 is defined

    - name: Download konstructs from bintray
      get_url:
        url: "{{ konstructs_jar_url }}"
        dest: "{{ konstructs_path }}/{{ konstructs_jar }}"
      notify: reload systemd and restart Konstructs
      when: konstructs_jar_sha256 is not defined

    - name: Setup systemd service for konstructs
      template:
        src: templates/konstructs.service.j2
        dest: /etc/systemd/system/konstructs.service
      notify: restart konstructs

    - name: Setup config for konstructs
      template:
        src: templates/konstructs.conf.j2
        dest: /opt/konstructs/konstructs.conf
      notify: restart konstructs

    - name: Setup redirect in nginx
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: reload nginx

- hosts: dev
  handlers:
    - name: reload systemd
      command: systemctl daemon-reload

  tasks:
    - name: Setup systemd socket and service for dev server reload
      template:
        src: "templates/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
      with_items:
        - update-konstructs.socket
        - update-konstructs@.service
      notify: reload systemd

    - name: Start update-konstructs.socket
      service: name=update-konstructs.socket state=started enabled=yes

    - name: Deploy update-konstructs script
      template:
        src: templates/update-konstructs.sh.j2
        dest: /usr/local/bin/update-konstructs
        mode: 0755
