---

- hosts: servers
  handlers:
    - name: reload systemd and restart Konstructs
      command: systemctl daemon-reload
      notify: restart konstructs
    - name: restart konstructs
      service: name=konstructs state=restarted enabled=yes

  tasks:
    - name: Install OpenJDK
      apt: name=openjdk-7-jre-headless update_cache=yes

    - name: Add konstructs user
      user:
        name: "{{ konstructs_user }}"
        comment: "A user for the konstructs game server"
        home: /opt/konstructs
        system: yes

    - name: Download konstructs from bintray (sha256 verify)
      get_url:
        sha256sum: "{{ konstructs_jar_sha256 }}"
        url: "{{ konstructs_jar_url }}"
        dest: "/opt/konstructs/{{ konstructs_jar }}"
      notify: reload systemd and restart Konstructs
      when: konstructs_jar_sha256 is defined

    - name: Download konstructs from bintray
      get_url:
        url: "{{ konstructs_jar_url }}"
        dest: "/opt/konstructs/{{ konstructs_jar }}"
      notify: reload systemd and restart Konstructs
      when: konstructs_jar_sha256 is not defined

    - name: Setup systemd service for konstructs
      template:
        src: templates/konstructs.service.j2
        dest: /etc/systemd/system/konstructs.service
      notify: restart konstructs

- hosts: dev
  handlers:
    - name: reload systemd
      command: systemctl daemon-reload

  tasks:
    - name: Setup systemd socket and service for dev server reload
      template:
        src: "templates/{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
      with_items:
        - update-konstructs.socket
        - update-konstructs@.service
      notify: reload systemd

    - name: Start update-konstructs.socket
      service: name=update-konstructs.socket state=started enabled=yes

    - name: Deploy update-konstructs script
      template:
        src: templates/update-konstructs.sh.j2
        dest: /usr/local/bin/update-konstructs
        mode: 0755
